apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-edge-aoa/
    targetRevision: aptt
    path: environments/demo/infra/overlay/crds/1.11/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
