apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-enterprise-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-ee
    helm:
      skipCrds: true
      values: |
        license_key: eyJleHAiOjE2NDUyMTAwMzQsImlhdCI6MTY0MjYxODAzNCwiayI6IjRlZTJEUSIsImx0IjoidHJpYWwiLCJwcm9kdWN0IjoiZ2xvbyJ9.1uwlkqzhwM9G_AksQgZNRMObduxKWKeEo-DLnNAk4-k
    repoURL: http://storage.googleapis.com/gloo-ee-helm
    targetRevision: 1.10.4
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true
