apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-edge-aoa/
    targetRevision: HEAD
    path: environments/demo/cluster-config/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false