apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: route-limit-foo
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 4
        unit: MINUTE
      value: count
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: count
---
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: route-limit-bar
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 4
        unit: MINUTE
      value: count
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: count
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /foo
      options:
        prefixRewrite: '/get'
        rateLimitConfigs:
          refs:
          - name: route-limit-foo
            namespace: gloo-system
        transformations:
          responseTransformation:
            transformationTemplate:
              headers:
                content-type:
                  text: '{{ request_header("content-type") }}'
                Accept-Encoding:
                  text: '{{ request_header("accept-encoding") }}'
                X-Device-Platform:
                  text: 'fooplatform'
                ":status":
                  text: '{% if header(":status") == "405" %}201{% else if header(":status") == "429" %}529{% else %}{{ header(":status") }}{% endif %}'    
              #body:
              #  text: '{% if header(":status") == "429" %}529 - rate limited{% else %}{{ header(":status") }}{% endif %}'
              body:
                text: '{% if header(":status") == "429" %}529 - rate limited{% else %}{{ body() }}{% endif %}'
              parseBodyBehavior: ParseAsJson
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
    - matchers:
      - prefix: /bar
      options:
        prefixRewrite: '/'
        rateLimitConfigs:
          refs:
          - name: route-limit-bar
            namespace: gloo-system
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system