apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bombardier
  name: bombardier
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombardier
  template:
    metadata:
      labels:
        app: bombardier
    spec:
      containers:
      - args:
        - -c
        - for run in $(seq 1 100); do bombardier -c 1 -d 60s -r 1 -p i,p,r http://gateway-proxy.gloo-system/productpage;
          done
        command:
        - /bin/sh
        image: alpine/bombardier
        imagePullPolicy: IfNotPresent
        name: bombardier