---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-httpbin-vs-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-edge-aoa/
    targetRevision: httpbin
    path: environments/demo/edge-config/non-active/httpbin/static/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}